/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CharactersInRegionModal: typeof import('./components/lists/CharactersInRegionModal.vue')['default']
    ClaimbuildsApplicationStep0: typeof import('./components/applications/Claimbuilds/ClaimbuildsApplicationStep0.vue')['default']
    ClaimbuildsApplicationStep1: typeof import('./components/applications/Claimbuilds/ClaimbuildsApplicationStep1.vue')['default']
    ClaimbuildsApplicationStep2: typeof import('./components/applications/Claimbuilds/ClaimbuildsApplicationStep2.vue')['default']
    ClaimbuildsApplicationStep3: typeof import('./components/applications/Claimbuilds/ClaimbuildsApplicationStep3.vue')['default']
    ClaimbuildsInRegionModal: typeof import('./components/lists/ClaimbuildsInRegionModal.vue')['default']
    DiscordIcon: typeof import('./components/icons/DiscordIcon.vue')['default']
    FactionDashboardActionCard: typeof import('./components/dashboards/factionDashboard/SummaryAndWars/FactionDashboardActionCard.vue')['default']
    FactionDashboardArmies: typeof import('./components/dashboards/factionDashboard/FactionDashboardArmies.vue')['default']
    FactionDashboardRegions: typeof import('./components/dashboards/factionDashboard/FactionDashboardRegions.vue')['default']
    FactionDashboardSummary: typeof import('./components/dashboards/factionDashboard/SummaryAndWars/FactionDashboardSummary.vue')['default']
    FactionDashboardSummaryInformation: typeof import('./components/dashboards/factionDashboard/SummaryAndWars/FactionDashboardSummaryInformation.vue')['default']
    FactionDashboardSummaryWar: typeof import('./components/dashboards/factionDashboard/SummaryAndWars/FactionDashboardSummaryWar.vue')['default']
    FactionDashboardSummaryWars: typeof import('./components/dashboards/factionDashboard/SummaryAndWars/FactionDashboardSummaryWars.vue')['default']
    FactionListCard: typeof import('./components/dashboards/factionDashboard/FactionListCard.vue')['default']
    FooterBar: typeof import('./components/navbars/FooterBar.vue')['default']
    InstagramIcon: typeof import('./components/icons/InstagramIcon.vue')['default']
    ListCard: typeof import('./components/lists/ListCard.vue')['default']
    RegistrationForm: typeof import('./components/RegistrationForm.vue')['default']
    RoleplayCharacterApplicationStep1: typeof import('./components/applications/RPCharApp/RoleplayCharacterApplicationStep1.vue')['default']
    RoleplayCharacterApplicationStep2: typeof import('./components/applications/RPCharApp/RoleplayCharacterApplicationStep2.vue')['default']
    RoleplayCharacterApplicationStep3: typeof import('./components/applications/RPCharApp/RoleplayCharacterApplicationStep3.vue')['default']
    RoleplayCharacterApplicationStep4: typeof import('./components/applications/RPCharApp/RoleplayCharacterApplicationStep4.vue')['default']
    RoleplayCharacterDetailsModal: typeof import('./components/lists/RoleplayCharacterDetailsModal.vue')['default']
    RoleplayDataCard: typeof import('./components/lists/RoleplayDataCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffButtonList: typeof import('./components/navbars/StaffButtonList.vue')['default']
    TopNavbar: typeof import('./components/navbars/TopNavbar.vue')['default']
    UserButtonList: typeof import('./components/navbars/UserButtonList.vue')['default']
    UserDashboardActionCard: typeof import('./components/dashboards/userDashboard/UserDashboardActionCard.vue')['default']
    UserDashboardActions: typeof import('./components/dashboards/userDashboard/UserDashboardActions.vue')['default']
    UserDashboardCard: typeof import('./components/dashboards/userDashboard/UserDashboardCard.vue')['default']
    UserDashboardCharacterBasicInfo: typeof import('./components/dashboards/userDashboard/UserDashboardCharacterBasicInfo.vue')['default']
    UserDashboardMainContent: typeof import('./components/dashboards/userDashboard/UserDashboardMainContent.vue')['default']
    UserDashboardUpperCards: typeof import('./components/dashboards/userDashboard/UserDashboardUpperCards.vue')['default']
    VerticalNavbar: typeof import('./components/navbars/VerticalNavbar.vue')['default']
  }
}
